name: Mergebot

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:
  
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
     - name: my-app-install token
       id: my-app
       uses: getsentry/action-github-app-token@v1
       with:
         app_id: ${{ secrets.APP_ID }}
         private_key: ${{ secrets.APP_PRIVATE_KEY }}

     - name: Checkout private repo
       uses: actions/checkout@v2
       with:
        repository: UBAID-DK/-e-conomic-mergebot-playground
        token: ${{ steps.my-app.outputs.token }}
        run: "Hi Ubaid ${ token }"
