name: Mergebot-UBR-0

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        app-id: ${{ secrets.APP_ID }} 
        TOKEN: ${{ steps.get-token.outputs.token }}
    - uses: e-conomic/mergebot@v1
      with:
        repository: UBAID-DK/-e-conomic-mergebot-playground
        token: ${{ steps.get-token.outputs.token }}
         
