name: Mergebot-UBR-0

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:
  
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
     - name: Generate token
       id: generate_token     
       uses: tibdex/github-app-token@v1      
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}          
     - name: Use token
       env:
          TOKEN: ${{ steps.generate_token.outputs.token }}     
          run: |
           "print token here { TOKEN } Ubaid Ur Rahman-1"
           "print token here  TOKEN  Ubaid Ur Rahman-2" 
           "print token here {{ TOKEN }} Ubaid Ur Rahman-3" 
           echo "The ***999 generated token is masked: ${TOKEN}"
     - name: economic area
       uses: e-conomic/mergebot@v1
       with:          
          github_token: ${ TOKEN }         
          semver_match: minors
          MERGE_METHOD: rebase
          run: "print token here ${{ TOKEN }} Ubaid Ur Rahman 101"  
         
