name: Mergebot-UBR-0

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: jarylc/github-app-token@v3.0.1
        with:
          app: ${{ secrets.APP_ID }}
          key: ${{ secrets.PRIVATE_KEY }}
          # Optional (defaults to the current owner)
          # owner: jarylc
      - name: Use Token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
         
