name: Mergebot-UBR-0

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:
  
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
     - name: Generate token
       id: generate_token     
       uses: tibdex/github-app-token@v1      
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}             
     - name: Use token
       env:
          appToken: ${{ steps.generate_token.outputs.token }}   
     - name: welcome
       uses: e-conomic/mergebot@v1
       with:
        github_token: ${ appToken }
        run: echo ubaid ${ appToken }
      
         
      

         
